server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lzc69/springcloud.git


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false